#!/usr/bin/env bash

APP="opencv_thumbnail_server" # name of your release

BUILD_HOST="192.168.212.210" # host where to build the release
BUILD_USER="ycc" # local user at build host
BUILD_AT="/tmp/erlang/builds" # build directory on build host

STAGING_HOSTS="192.168.212.210" # staging / test hosts separated by space
STAGING_USER="ycc" # local user at staging hosts
TEST_AT="/srv/telegram/deploy" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="144.0.3.52" # deploy / production hosts separated by space
PRODUCTION_USER="root" # local user at deploy hosts
DELIVER_TO="/srv/telegram/deploy" # deploy directory on production hosts


#LINK_SYS_CONFIG=/srv/opencv_thumbnail_server/rel/sys.config
LINK_VM_ARGS=/srv/opencv_thumbnail_server/rel/vm.args
